language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install -n
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:update --force
  - php app/console doctrine:fixtures:load --no-interaction
script: phpunit -c app
