parameters:
#    afpa_menu.example.class: Afpa\MenuBundle\Example

services:
#    afpa_menu.example:
#        class: %afpa_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
